# NAME: MAHMOUD OSAMA HASSAN ALSAGGA
## ID: 120255986

# Telecom Customer Churn Analysis

## Final Project
Data Science Programming Languages Lab

This project analyzes customer churn data from a telecommunications company.
The project covers data loading, Python fundamentals, object-oriented programming,
exception handling, NumPy, Pandas data cleaning, data analysis, and Excel export.

In [1]:

import numpy as np
import pandas as pd
import openpyxl

# Task 2: Kaggle API & Data Loading

In [2]:
!kaggle datasets download -d blastchar/telco-customer-churn --unzip

Dataset URL: https://www.kaggle.com/datasets/blastchar/telco-customer-churn
License(s): copyright-authors
Downloading telco-customer-churn.zip to c:\Users\User\Telecom_Customer_Churn_Project

  0%|          | 0.00/172k [00:00<?, ?B/s]
100%|██████████| 172k/172k [00:00<00:00, 179kB/s]
100%|██████████| 172k/172k [00:00<00:00, 179kB/s]

In [3]:
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
print(df.shape)

(7043, 21)

In [4]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [6]:
df.dtypes

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

## Brief Explanation.
Each row represents a single customer of a telecommunications company. It includes customer information, the services they use, payment details, and whether they left the company (Churn).

# Task 3: Python Core Skills

In [7]:
id_first_20 = df.head(20)['customerID'].tolist()
print(id_first_20)

['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', '7795-CFOCW', '9237-HQITU', '9305-CDSKC', '1452-KIOVK', '6713-OKOMC', '7892-POOKP', '6388-TABGU', '9763-GRSKD', '7469-LKBCI', '8091-TTVAX', '0280-XJGEX', '5129-JLPIS', '3655-SNQYZ', '8191-XWSZG', '9959-WOFKT', '4190-MFLUW', '4183-MYFRB']

In [8]:
m_charges_first_20 =df.head(20)["MonthlyCharges"].tolist()
customer_charge_dict = dict(zip(id_first_20,m_charges_first_20))

print(f"(ID : Charges): {customer_charge_dict}\n")

rounded_charges = list(map(lambda charge: round(charge), m_charges_first_20))

print(f"Charges with fractions: {rounded_charges}\n")

charges_above_80 = list(filter(lambda charge : charge > 80 , rounded_charges))
print(f"Charges more than 80: {charges_above_80}\n")

sorted_by_m_charges = sorted(customer_charge_dict.items() , key= lambda item : item[1], reverse=True)
print(f"Customer ID sorted by monthly charges: {sorted_by_m_charges}\n")

high_charge_customers = [customer_id for customer_id, charge in customer_charge_dict.items() if charge > 80]

print(high_charge_customers)

(ID : Charges): {'7590-VHVEG': 29.85, '5575-GNVDE': 56.95, '3668-QPYBK': 53.85, '7795-CFOCW': 42.3, '9237-HQITU': 70.7, '9305-CDSKC': 99.65, '1452-KIOVK': 89.1, '6713-OKOMC': 29.75, '7892-POOKP': 104.8, '6388-TABGU': 56.15, '9763-GRSKD': 49.95, '7469-LKBCI': 18.95, '8091-TTVAX': 100.35, '0280-XJGEX': 103.7, '5129-JLPIS': 105.5, '3655-SNQYZ': 113.25, '8191-XWSZG': 20.65, '9959-WOFKT': 106.7, '4190-MFLUW': 55.2, '4183-MYFRB': 90.05}

Charges with fractions: [30, 57, 54, 42, 71, 100, 89, 30, 105, 56, 50, 19, 100, 104, 106, 113, 21, 107, 55, 90]

Charges more than 80: [100, 89, 105, 100, 104, 106, 113, 107, 90]

Customer ID sorted by monthly charges: [('3655-SNQYZ', 113.25), ('9959-WOFKT', 106.7), ('5129-JLPIS', 105.5), ('7892-POOKP', 104.8), ('0280-XJGEX', 103.7), ('8091-TTVAX', 100.35), ('9305-CDSKC', 99.65), ('4183-MYFRB', 90.05), ('1452-KIOVK', 89.1), ('9237-HQITU', 70.7), ('5575-GNVDE', 56.95), ('6388-TABGU', 56.15), ('4190-MFLUW', 55.2), ('3668-QPYBK', 53.85), ('9763-GRSKD', 49.95), ('7795-CFOCW', 42.3), ('7590-VHVEG', 29.85), ('6713-OKOMC', 29.75), ('8191-XWSZG', 20.65), ('7469-LKBCI', 18.95)]

['9305-CDSKC', '1452-KIOVK', '7892-POOKP', '8091-TTVAX', '0280-XJGEX', '5129-JLPIS', '3655-SNQYZ', '9959-WOFKT', '4183-MYFRB']

In [9]:
def av_of_charges(charges):
    """
    Calculate and return the average of the given monthly charges.
    Return 0 when the list is empty.
    """
    if not charges:
        return 0

    return sum(charges) / len(charges)

print(f"Average monthly charges: {av_of_charges(m_charges_first_20)}")

Average monthly charges: 69.87

# Task 4: Object-Oriented Programming

In [10]:
class InvalidMonthlyChargeError(Exception):
    """Raised when monthly charges are negative."""    # from task 5 
    pass

from abc import ABC,abstractmethod
class Customer(ABC):
    def __init__(self, customer_id, tenure, monthly_charges):
        self.customer_id = customer_id
        self.tenure = tenure
        self.monthly_charges = monthly_charges
    @property
    def monthly_charges(self):
        return self._monthly_charges
    @monthly_charges.setter
    def monthly_charges(self, new_charge):
        if new_charge >= 0:
            self._monthly_charges = new_charge
        else:
            raise InvalidMonthlyChargeError("Monthly charges cannot be negative.")   # from task 5

    @abstractmethod
    def display_status(self):
        pass
    
    @abstractmethod
    def is_churn(self):
        pass

class ActiveCustomer(Customer):
    def is_churn(self):
        return False

    def display_status(self):
        return f"Customer {self.customer_id} is Active"

class ChurnCustomer(Customer):
    def is_churn(self):
        return True
    
    def display_status(self):
        return f"Customer {self.customer_id} is Churn"
    

mahmoud = ActiveCustomer(123 , 3 , 50)
print(mahmoud.is_churn())
print(mahmoud.display_status())
try:
    mahmoud.monthly_charges = -1
except Exception as e:
    print(e)

False
Customer 123 is Active
Monthly charges cannot be negative.

# Task 5: Exception Handling

In [11]:
class InvalidMonthlyChargeError(Exception):
    """Raised when monthly charges are negative."""
    pass
# used in the above cell

# Task 6: NumPy Operations

In [12]:
# first 2 required operation
import numpy as np

monthly_charges = df["MonthlyCharges"].values
tenure = df["tenure"].values

print(monthly_charges)
print(tenure)
estimated_total = monthly_charges * tenure

print(estimated_total)

[ 29.85  56.95  53.85 ...  29.6   74.4  105.65]
[ 1 34  2 ... 11  4 66]
[  29.85 1936.3   107.7  ...  325.6   297.6  6972.9 ]

In [13]:
long_term_customers = tenure[tenure > 12] # more than 12 months

print(long_term_customers)

[34 45 22 ... 24 72 66]

In [14]:
print("Monthly Charges Statistics")
print("Mean:", np.mean(monthly_charges))
print("Minimum:", np.min(monthly_charges))
print("Maximum:", np.max(monthly_charges))
print("Standard Deviation:", np.std(monthly_charges))

print()

print("Tenure Statistics")
print("Mean:", np.mean(tenure))
print("Minimum:", np.min(tenure))
print("Maximum:", np.max(tenure))
print("Standard Deviation:", np.std(tenure))

Monthly Charges Statistics
Mean: 64.76169246059918
Minimum: 18.25
Maximum: 118.75
Standard Deviation: 30.087910854936975

Tenure Statistics
Mean: 32.37114865824223
Minimum: 0
Maximum: 72
Standard Deviation: 24.55773742286344

# Task 7: Pandas Data Cleaning

#### save the original data without changes

In [15]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [16]:
clean_df = df.copy()

#### clean columns names

In [17]:
clean_df.columns = clean_df.columns.str.strip().str.lower()
print(df.columns)

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

#### clean and replace descriptive names

In [18]:
clean_df = clean_df.rename(
    columns={
        "customerid": "customer_id",
        "seniorcitizen": "senior_citizen",
        "phoneservice": "phone_service",
        "multiplelines": "multiple_lines",
        "internetservice": "internet_service",
        "onlinesecurity": "online_security",
        "onlinebackup": "online_backup",
        "deviceprotection": "device_protection",
        "techsupport": "tech_support",
        "streamingtv": "streaming_tv",
        "streamingmovies": "streaming_movies",
        "paperlessbilling": "paperless_billing",
        "paymentmethod": "payment_method",
        "monthlycharges": "monthly_charges",
        "totalcharges": "total_charges",
        "partner"     : "is_marred"    # descriptive
    }
)
print(clean_df.columns)
print(clean_df["total_charges"].dtype)

Index(['customer_id', 'gender', 'senior_citizen', 'is_marred', 'dependents',
       'tenure', 'phone_service', 'multiple_lines', 'internet_service',
       'online_security', 'online_backup', 'device_protection', 'tech_support',
       'streaming_tv', 'streaming_movies', 'contract', 'paperless_billing',
       'payment_method', 'monthly_charges', 'total_charges', 'churn'],
      dtype='str')
str

#### Missing Values: Identify and handle: drop, fill, or impute

In [19]:
# since total_charges is str then I need to convert its type before

clean_df["total_charges"] = pd.to_numeric(clean_df["total_charges"], errors="coerce")
print(clean_df.duplicated().sum())
print(clean_df["total_charges"].dtype)

# 4. Identify missing values
print("\nMissing values before handling:")
print(clean_df.isnull().sum())



# 5. Handle missing values

# Fill missing total_charges values with the median.

total_charges_median = clean_df["total_charges"].median()

clean_df["total_charges"] = clean_df["total_charges"].fillna(total_charges_median)

print("\nMissing values after handling:")
print(clean_df.isnull().sum())

0
float64

Missing values before handling:
customer_id           0
gender                0
senior_citizen        0
is_marred             0
dependents            0
tenure                0
phone_service         0
multiple_lines        0
internet_service      0
online_security       0
online_backup         0
device_protection     0
tech_support          0
streaming_tv          0
streaming_movies      0
contract              0
paperless_billing     0
payment_method        0
monthly_charges       0
total_charges        11
churn                 0
dtype: int64

Missing values after handling:
customer_id          0
gender               0
senior_citizen       0
is_marred            0
dependents           0
tenure               0
phone_service        0
multiple_lines       0
internet_service     0
online_security      0
online_backup        0
device_protection    0
tech_support         0
streaming_tv         0
streaming_movies     0
contract             0
paperless_billing    0
payment_method       0
monthly_charges      0
total_charges        0
churn                0
dtype: int64

#### Duplicates: Detect and remove duplicate rows

In [20]:

# 6. Detect and remove duplicate rows

duplicate_count = clean_df.duplicated().sum()

print("\nNumber of duplicate rows before cleaning:")
print(duplicate_count)

# Remove duplicated rows to avoid repeated customer records.
clean_df = clean_df.drop_duplicates()

print("\nNumber of duplicate rows after cleaning:")
print(clean_df.duplicated().sum())

Number of duplicate rows before cleaning:
0

Number of duplicate rows after cleaning:
0

####  Convert data types

In [21]:
# Convert total_charges to numeric
clean_df["total_charges"] = pd.to_numeric(
    clean_df["total_charges"],
    errors="coerce"
)

# Convert Yes/No columns to boolean
boolean_columns = [
    "is_marred",
    "dependents",
    "phone_service",
    "paperless_billing",
    "churn"
]

for column in boolean_columns:
    clean_df[column] = clean_df[column].map({"Yes": True,"No": False})

# Convert 0/1 column to boolean
clean_df["senior_citizen"] = clean_df["senior_citizen"].astype(bool)

# Convert categorical columns
category_columns = [
    "gender",
    "multiple_lines",
    "internet_service",
    "online_security",
    "online_backup",
    "device_protection",
    "tech_support",
    "streaming_tv",
    "streaming_movies",
    "contract",
    "payment_method"
]

for column in category_columns:
    clean_df[column] = clean_df[column].astype("category")

#### Consistency: Standardize text values (e.g., lowercase, trim whitespace)

In [22]:
# Select all text columns.
text_columns = clean_df.select_dtypes(include="str").columns

# Remove extra spaces and convert text to lowercase.
for column in text_columns:
    clean_df[column] = clean_df[column].str.strip().str.lower()

#### Outliers: Note any extreme values (optional: handle them)

In [23]:

# Detect possible outliers

# Use the IQR method to identify possible outliers
# in the monthly_charges column.
q1 = clean_df["monthly_charges"].quantile(0.25)
q3 = clean_df["monthly_charges"].quantile(0.75)

iqr = q3 - q1

lower_bound = q1 - (1.5 * iqr)
upper_bound = q3 + (1.5 * iqr)

monthly_charge_outliers = clean_df[(clean_df["monthly_charges"] < lower_bound)|(clean_df["monthly_charges"] > upper_bound)]

print("\nNumber of possible monthly charge outliers:")
print(len(monthly_charge_outliers))

# The outliers are not removed because high monthly charges
# may represent valid premium service plans rather than incorrect data.

Number of possible monthly charge outliers:
0

#### Result

In [24]:
# Final verification

print("\nCleaned dataset shape:")
print(clean_df.shape)

print("\nCleaned dataset data types:")
print(clean_df.dtypes)

print("\nFirst five rows of the cleaned dataset:")
print(clean_df.head())

Cleaned dataset shape:
(7043, 21)

Cleaned dataset data types:
customer_id               str
gender               category
senior_citizen           bool
is_marred                bool
dependents               bool
tenure                  int64
phone_service            bool
multiple_lines       category
internet_service     category
online_security      category
online_backup        category
device_protection    category
tech_support         category
streaming_tv         category
streaming_movies     category
contract             category
paperless_billing        bool
payment_method       category
monthly_charges       float64
total_charges         float64
churn                    bool
dtype: object

First five rows of the cleaned dataset:
  customer_id  gender  senior_citizen  is_marred  dependents  tenure  \
0  7590-vhveg  Female           False       True       False       1
1  5575-gnvde    Male           False      False       False      34
2  3668-qpybk    Male           False      False       False       2
3  7795-cfocw    Male           False      False       False      45
4  9237-hqitu  Female           False      False       False       2

   phone_service    multiple_lines internet_service online_security  ...  \
0          False  No phone service              DSL              No  ...
1           True                No              DSL             Yes  ...
2           True                No              DSL             Yes  ...
3          False  No phone service              DSL             Yes  ...
4           True                No      Fiber optic              No  ...

  device_protection tech_support streaming_tv streaming_movies  \
0                No           No           No               No
1               Yes           No           No               No
2                No           No           No               No
3               Yes          Yes           No               No
4                No           No           No               No

         contract paperless_billing             payment_method  \
0  Month-to-month              True           Electronic check
1        One year             False               Mailed check
2  Month-to-month              True               Mailed check
3        One year             False  Bank transfer (automatic)
4  Month-to-month              True           Electronic check

  monthly_charges  total_charges  churn
0           29.85          29.85  False
1           56.95        1889.50  False
2           53.85         108.15   True
3           42.30        1840.75  False
4           70.70         151.65   True

[5 rows x 21 columns]

# Task 8: Data Analysis

### Which customers have high monthly charges?
### Which contract type has the highest average monthly charges?
### How many customers churned and how many remained?
### How many customers use each payment method?

In [25]:
# Filtering
high_charge = clean_df[
    clean_df["monthly_charges"] > 80
]

print(high_charge.head())
print("Number of customers with hight charges:", len(high_charge))
#This analysis filters customers with monthly charges greater than 80. 
# These customers represent the highest-paying group and may require further analysis to determine whether they are more likely to churn.
#  Understanding this group can help the company improve customer retention.

   customer_id  gender  senior_citizen  is_marred  dependents  tenure  \
5   9305-cdskc  Female           False      False       False       8
6   1452-kiovk    Male           False      False        True      22
8   7892-pookp  Female           False       True       False      28
12  8091-ttvax    Male           False       True       False      58
13  0280-xjgex    Male           False      False       False      49

    phone_service multiple_lines internet_service online_security  ...  \
5            True            Yes      Fiber optic              No  ...
6            True            Yes      Fiber optic              No  ...
8            True            Yes      Fiber optic              No  ...
12           True            Yes      Fiber optic              No  ...
13           True            Yes      Fiber optic              No  ...

   device_protection tech_support streaming_tv streaming_movies  \
5                Yes           No          Yes              Yes
6                 No           No          Yes               No
8                Yes          Yes          Yes              Yes
12               Yes           No          Yes              Yes
13               Yes           No          Yes              Yes

          contract paperless_billing             payment_method  \
5   Month-to-month              True           Electronic check
6   Month-to-month              True    Credit card (automatic)
8   Month-to-month              True           Electronic check
12        One year             False    Credit card (automatic)
13  Month-to-month              True  Bank transfer (automatic)

   monthly_charges  total_charges  churn
5            99.65         820.50   True
6            89.10        1949.40  False
8           104.80        3046.05   True
12          100.35        5681.10  False
13          103.70        5036.30   True

[5 rows x 21 columns]
Number of customers with hight charges: 2666

In [26]:
#Grouping + Aggregation + Sorting
# that show the mean charges for every type of contract
contract_analysis = (
    clean_df.groupby("contract")["monthly_charges"]
    .mean()
    .sort_values(ascending=False)
)

print(contract_analysis)
#This analysis compares the average monthly charges for each contract type. 
# Sorting the results makes it easy to identify which contract has the highest average charges.
#  These insights can help the company understand customer spending patterns across different contracts.

contract
Month-to-month    66.398490
One year          65.048608
Two year          60.770413
Name: monthly_charges, dtype: float64

In [27]:
number_of_churn = clean_df["churn"].sum()
number_of_active = len(clean_df) - number_of_churn

print(f"Number of churn customers: {number_of_churn}")
print(f"Number of active customers: {number_of_active}")
#This analysis shows the number of customers who stayed with the company and those who left.
#  Comparing these two groups helps evaluate customer retention and the overall churn rate.
#  The results can support future strategies to reduce customer loss.

Number of churn customers: 1869
Number of active customers: 5174

In [28]:
payment_count = (
    clean_df.groupby("payment_method")["customer_id"]
    .count()
    .sort_values(ascending=False)
)

print(payment_count)
# This analysis counts the number of customers using each payment method.
#  It helps identify the most commonly used payment option. 
# These results can support decisions related to billing and payment services.

payment_method
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: customer_id, dtype: int64

# Task 9: Excel Export

In [29]:

# Summary sheet
summary = pd.DataFrame({
    "Finding": [
        "High charge customers",
        "Contract with highest average monthly charges",
        "Most common payment method"    ],
    "Result": [
        len(high_charge),
        contract_analysis.idxmax(),
        payment_count.idxmax()
    ]
})

# Export to Excel
with pd.ExcelWriter("Project_Report.xlsx", engine="openpyxl") as writer:
    clean_df.to_excel(writer, sheet_name="Cleaned Data", index=False)

    contract_analysis.to_frame(
        name="Average Monthly Charges"
    ).to_excel(writer, sheet_name="Analysis", startrow=0)

    payment_count.to_frame(
        name="Customer Count"
    ).to_excel(writer, sheet_name="Analysis", startrow=6)

    summary.to_excel(writer, sheet_name="Summary", index=False)

print("Project_Report.xlsx created successfully!")

Project_Report.xlsx created successfully!

In [30]:
from openpyxl import load_workbook
from openpyxl.styles import Font

wb = load_workbook("Project_Report.xlsx")

for sheet in wb.sheetnames:
    ws = wb[sheet]

    # Bold headers
    for cell in ws[1]:
        cell.font = Font(bold=True)

    # Adjust column widths
    for column in ws.columns:
        length = max(len(str(cell.value)) if cell.value is not None else 0 for cell in column)
        ws.column_dimensions[column[0].column_letter].width = length + 2

# Add title to Summary sheet
summary_ws = wb["Summary"]
summary_ws.insert_rows(1)
summary_ws["A1"] = "Telco Customer Churn - Project Summary"
summary_ws["A1"].font = Font(bold=True, size=14)

wb.save("Project_Report.xlsx")

## Conclusion

The analysis showed that customers with month-to-month contracts have different monthly charge patterns compared with customers using longer contracts.
It also identified the most commonly used payment method and the number of customers with high monthly charges.

These findings can help the company better understand customer behaviour and improve its pricing, contract, and payment strategies.

## Future Analysis

Future analysis could examine the relationship between monthly charges, contract type, and customer churn.
 A machine learning model could also be developed to predict which customers are most likely to leave the company.